Add ammo types
ratenbuuren/ProjectBeard pull request #49
Opened 2017-08-01 18:48 UTC by kdhageman

2017-08-14 18:41 UTC, ratenbuuren commented
Had a quick play-through, some minor things:
- Tanks now also pass trough obstacles/boxes
- Add UI for ammo type?

2017-08-14 18:55 UTC, ratenbuuren requested changes
Looks great. Nice setup. Some really minor things for improving next to my other comment.

2017-08-14 18:55 UTC, ratenbuuren commented on Assets/Scripts/Projectiles/ProjectileController.cs
> +    public float damageModifier = 1f;
No consistent naming (Rider style) in this class

2017-08-14 18:55 UTC, ratenbuuren commented on Assets/Scripts/Prefabs/DestroyAfterTime.cs
> +    // Use this for initialization
Remove comment

2017-08-14 18:55 UTC, ratenbuuren commented on Assets/Scripts/GameManager.cs
> +using System;
Much better ;)

2017-08-15 07:00 UTC, kdhageman commented on Assets/Scripts/GameManager.cs
> +using System;
Hm, when I revert this change, Rider does not recognise `NullPointerException`.

2017-08-15 07:06 UTC, kdhageman commented
@ratenbuuren Good idea to add ammo type to the UI. It's outside of the scope of this PR, so I'll add a new issue.

2017-08-15 17:54 UTC, ratenbuuren approved these changes

2017-08-15 17:54 UTC, merged